## 1. Create a program that asks the user to enter their name and their age. Print out a message that tells them the year that they will turn 100 years old

In [1]:
from datetime import datetime
name = input('What is your name? \n')
age = int(input('How old are you? \n'))
hundred = int((100-age) + datetime.now().year)
print ('Hello %s. You are %s years old. You will turn 100 years old in %s.' % (name, age, hundred))

What is your name? 
Rajesh
How old are you? 
34
Hello Rajesh. You are 34 years old. You will turn 100 years old in 2088.


# 2.What is pandas groupby? Demonstrate with your own example

###### 1.Group by is an aggregate function which is used to do sum , mean, median ,standard deviation, min ,max calculation to find the value of group

In [6]:
import pandas as pd
import numpy as np


In [26]:
import warnings
warnings.filterwarnings('ignore')

In [13]:
Test_data = {'cust id':[25,26,25,23,30],' Cust Name':['Rajesh','Ramesh','Murali','Vinoth','Selva'],'Salary':[3000,5000,2500,7800,6000]}
Test_data1 = pd.DataFrame(Test_data)
Test_data1

cust id  Cust Name  Salary
0       25     Rajesh    3000
1       26     Ramesh    5000
2       25     Murali    2500
3       23     Vinoth    7800
4       30      Selva    6000

In [20]:
Test_data1['Bonus'] = pd.Series([1000,5000,4000,2000,1500])

In [21]:
Test_data1

cust id  Cust Name  Salary  Bonus
0       25     Rajesh    3000   1000
1       26     Ramesh    5000   5000
2       25     Murali    2500   4000
3       23     Vinoth    7800   2000
4       30      Selva    6000   1500

In [17]:
Test_data1.groupby(['cust id'])['Salary'].sum()

cust id
23    7800
25    5500
26    5000
30    6000
Name: Salary, dtype: int64

In [27]:
Test_data1.groupby(['cust id'])['Salary','Bonus'].mean()

Salary   Bonus
cust id                
23       7800.0  2000.0
25       2750.0  2500.0
26       5000.0  5000.0
30       6000.0  1500.0

# 3. How to create a dataframe from list?
       1. By using series we can create a list 
       2. by using dictonary we can create list to convert list as dataframe
       2. By using columns we can create list , reindex we can alter list of index

In [28]:
Test_data = {'cust id':[25,26,25,23,30],' Cust Name':['Rajesh','Ramesh','Murali','Vinoth','Selva'],'Salary':[3000,5000,2500,7800,6000]}
Test_data1 = pd.DataFrame(Test_data)
Test_data1

cust id  Cust Name  Salary
0       25     Rajesh    3000
1       26     Ramesh    5000
2       25     Murali    2500
3       23     Vinoth    7800
4       30      Selva    6000

# 4.What are the ways to combine the dataframe in pandas. Give an example for each
   1. By using merge 
   2. By using concat

In [29]:
data_left= {'id':[1,2,3,4,5,6,7],'Name':['Tom','James','Ricky','Vim','Steve','Smith','Jack'],
        'Subject':['CSA','Telegu','Maths','Chemistry','Physics','Botany','zeology']}
df2=pd.DataFrame(data_left)
df2

id   Name    Subject
0   1    Tom        CSA
1   2  James     Telegu
2   3  Ricky      Maths
3   4    Vim  Chemistry
4   5  Steve    Physics
5   6  Smith     Botany
6   7   Jack    zeology

In [30]:
data_right= {'id':[1,2,3,4,5,6,7],'Name':['Rajesh','Ramesh','Ricky','Vim','Murali','Kiran','Jack'],
        'Subject':['Telegu','Tamil','Maths','Physics','Chemistry','Botany','EVS']}
df3=pd.DataFrame(data_right)
df3

id    Name    Subject
0   1  Rajesh     Telegu
1   2  Ramesh      Tamil
2   3   Ricky      Maths
3   4     Vim    Physics
4   5  Murali  Chemistry
5   6   Kiran     Botany
6   7    Jack        EVS

In [31]:
pd.merge(df2,df3, on='id')

id Name_x  Subject_x  Name_y  Subject_y
0   1    Tom        CSA  Rajesh     Telegu
1   2  James     Telegu  Ramesh      Tamil
2   3  Ricky      Maths   Ricky      Maths
3   4    Vim  Chemistry     Vim    Physics
4   5  Steve    Physics  Murali  Chemistry
5   6  Smith     Botany   Kiran     Botany
6   7   Jack    zeology    Jack        EVS

In [32]:
pd.concat([df2,df3], axis=1)

id   Name    Subject  id    Name    Subject
0   1    Tom        CSA   1  Rajesh     Telegu
1   2  James     Telegu   2  Ramesh      Tamil
2   3  Ricky      Maths   3   Ricky      Maths
3   4    Vim  Chemistry   4     Vim    Physics
4   5  Steve    Physics   5  Murali  Chemistry
5   6  Smith     Botany   6   Kiran     Botany
6   7   Jack    zeology   7    Jack        EVS

# 5. What is the difference between list and tuples in Python?
      1. List : list is mutable and unordered collection. needs to create extra memory block for adding list
      2.tuples: tuples is immutable and ordered collection. fixed memoery since immutable

In [34]:
list = [[1,2,3,4],[1,3,'raj','simbu']]

In [35]:
list

[[1, 2, 3, 4], [1, 3, 'raj', 'simbu']]

In [40]:
a=10
list.insert(0,a)

In [41]:
list

[10, [1, 2, 3, 4], [1, 3, 'raj', 'simbu'], 10]

In [43]:
tuple1 = 'Rajesh','Ramesh', 'nine'
print(tuple1)

('Rajesh', 'Ramesh', 'nine')


# 6. Find out the mean, median and standard deviation of this numpy array -> np.array([1,5,3,100,4,48])

In [44]:
Test_npdata =np.array([1,5,3,100,4,48])

In [47]:
Test_npdata

array([  1,   5,   3, 100,   4,  48])

In [49]:
print(np.mean(Test_npdata))
print(np.median(Test_npdata))
print(np.std(Test_npdata))

26.833333333333332
4.5
36.59424666377065


# 7. How will you remove duplicate elements from a list?

In [50]:
list1 = [5,6,4,5,5,6,9,10]

In [53]:
list1

[5, 6, 4, 5, 5, 6, 9, 10]

In [58]:
list2 =[]
for i in list1:
    if i not in list2:
        list2.append(i)
print('The list removed duplicate',(list2))

The list removed duplicate [5, 6, 4, 9, 10]


# 8. What is a map() function in Python? Give an example
           map is an anonymnous function . it means function passing a list of parameter it wil compute a list given as result

In [100]:
def square(x):
    return x*x

In [101]:
list = [5,6,8,9,10]

In [102]:
result = map(square, list)

In [103]:
print(next(result))

25


# 9. What is pass in Python?
     Pass is keyword we can implement code in later for that function. nothing happens when executed

In [76]:
for letter in 'Rajesh':
    if letter == 'j':
        pass
        print('The Name of word pass')
    print("Rest of the word",letter)
print('Complete code')

Rest of the word R
Rest of the word a
The Name of word pass
Rest of the word j
Rest of the word e
Rest of the word s
Rest of the word h
Complete code


# 10. What is vstack() in numpy? Give an example
           Append the data vertically for single column. cancatation of array in to column wise


In [78]:
a = np.array([1,2,3,4,5])
b = np.array([10,20,30,40,50])
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40, 50]])

In [82]:
c = np.array([[1],[2],[3],[4]])
d = np.array([[6],[7],[8],[9]])
np.vstack((c,d))

array([[1],
       [2],
       [3],
       [4],
       [6],
       [7],
       [8],
       [9]])